import{S as b,i as n}from"./assets/vendor-DpP3Vvmc.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))a(r);new MutationObserver(r=>{for(const s of r)if(s.type==="childList")for(const f of s.addedNodes)f.tagName==="LINK"&&f.rel==="modulepreload"&&a(f)}).observe(document,{childList:!0,subtree:!0});function e(r){const s={};return r.integrity&&(s.integrity=r.integrity),r.referrerPolicy&&(s.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?s.credentials="include":r.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function a(r){if(r.ep)return;r.ep=!0;const s=e(r);fetch(r.href,s)}})();const w="52591555-089c8d48efe1c098578f49548",E="https://pixabay.com/api/",m=15;async function y(t,o=1){const e=new URL(E);e.searchParams.set("key",w),e.searchParams.set("q",t),e.searchParams.set("image_type","photo"),e.searchParams.set("orientation","horizontal"),e.searchParams.set("safesearch","true"),e.searchParams.set("per_page",String(m)),e.searchParams.set("page",String(o));try{const a=await fetch(e.toString());if(!a.ok)throw new Error(`Pixabay API error: ${a.status}`);return await a.json()}catch(a){throw a}}const i={gallery:document.getElementById("gallery"),loadMoreBtn:document.getElementById("load-more"),loader:document.getElementById("loader")},P=new b(".gallery a",{captionsData:"alt",captionDelay:250});function p(t){if(!Array.isArray(t)||t.length===0)return;const o=t.map(e=>`
      <div class="photo-card">
        <a href="${e.largeImageURL}">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span>${e.likes}</span></p>
          <p class="info-item"><b>Views</b><span>${e.views}</span></p>
          <p class="info-item"><b>Comments</b><span>${e.comments}</span></p>
          <p class="info-item"><b>Downloads</b><span>${e.downloads}</span></p>
        </div>
      </div>
    `).join("");i.gallery.insertAdjacentHTML("beforeend",o),P.refresh()}function v(){i.gallery.innerHTML=""}function g(){i.loader.classList.remove("hidden")}function u(){i.loader.classList.add("hidden")}function L(){i.loadMoreBtn.classList.remove("hidden")}function l(){i.loadMoreBtn.classList.add("hidden")}const B=document.getElementById("search-form"),A=document.getElementById("search-input"),S=i.loadMoreBtn,M=i.gallery;let h="",c=1,d=0;B.addEventListener("submit",I);S.addEventListener("click",$);async function I(t){t.preventDefault();const o=A.value.trim();if(!o){n.warning({title:"Warning",message:"Please enter a search query."});return}h=o,c=1,d=0,v(),l();try{g();const e=await y(h,c);if(u(),!e||!Array.isArray(e.hits)||e.hits.length===0){n.info({title:"No results",message:"No images found. Try another query."});return}p(e.hits),d=e.totalHits,c*m<d?L():(l(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."})),n.success({title:"Success",message:`Found ${d} images.`})}catch(e){u(),console.error(e),n.error({title:"Error",message:"Something went wrong. Please try again later."})}}async function $(){c+=1,l(),g();try{const t=await y(h,c);if(u(),!t||!Array.isArray(t.hits)||t.hits.length===0){l(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."});return}p(t.hits),q(),c*m>=t.totalHits?(l(),n.info({title:"End",message:"We're sorry, but you've reached the end of search results."})):L()}catch(t){u(),console.error(t),n.error({title:"Error",message:"Failed to load more images."})}}function q(){const t=M.querySelector(".photo-card");if(!t)return;const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
